config/routes.rb
Rails.application.routes.draw do
  
  root 'homes#top'
  get 'homes/about'
  get 'rooms/show'
  get 'rooms/index'
  
  devise_for :companys, controller: {
    sessions: "companys/sessions",
    passwords: "companys/passwords",
    registrations: "companys/registration"
 }
  
  resources :company, only:[:show, :edit, :update]
  
  get 'contacts/index'
  get 'contacts/confirm'
  get 'contacts/thanks'
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
  
  
  namespace :personal do
    resources :users, only:[:show, :edit, :update]
  end


  resources :posts do
      resource :favorites, only: [:create, :destroy]
  end
    
  get 'contacts' => 'contacts#index'
  post 'contacts/confirm' => 'contacts#confirm'
  post 'contacts/thanks' => 'contacts#thanks'


  resources :rooms, :only => [:index, :show, :create] do
    resources :messages, :only => [:create]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :rooms
  has_many :favorites, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  attachment :company_image
end

app/models/contact.rb
class Contact < ApplicationRecord
     include ActiveModel::Model
     attr_accessor :name, :email, :message
     
      validates :name, presence: true
      validates :email, presence: true
      validates :message, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :company
  belongs_to :post
end

app/models/message.rb
class Message < ApplicationRecord
    validates :content, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
    
    has_many :favorites, dependent: :destroy
    belongs_to :user
    
    validates :title, presence: true
    validates :description, presence: true
    
    attachment :post_image
  
  
  def favorited_by?(company)
    favorites.where(company_id: company.id).exists?
  end
  
end

app/models/room.rb
class Room < ApplicationRecord
    has_many :messages
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :rooms, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  attachment :profile_image
end

app/controllers/company_controller.rb
class CompanyController < ApplicationController
  
  def show
    @company = Company.find(params[:id])
    @favorites = Favorite.where(company_id: @company.id)
  end

  def edit
    @company = Company.find(params[:id])
  end

  def update
    @company = Company.find(params[:id])
    @company.update(company_params)
    redirect_to company_path(@company)
  end
  
  private
  def company_params
    params.require(:company).permit(:company_name, :description, :company_image)
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
    @contact = Contact.new
    render :action => 'index'
  end

  def confirm
    @contact = Contact.new(contact_params)
    if @contact.valid?
      render :action => 'confirm'
    else
      render :action => 'index'
    end
  end

  def thanks
    
    @contact = Contact.new(contact_params)
    
    ContactMailer.received_email(@contact).deliver
  
    
    render :action => 'thanks'
  end
  
  def contact_params
    params.require(:contact).permit(
      :name, :email, :message
    )
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
  def top
  @skip_footer = true
  end

  def about
  end
  
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    
    def create
        @room = Room.find(params[:room_id])
        @message = Message.new(message_params)
        #メッセージがuserによるものだったらis_user=true, companyによるものだったらis_user=false
    if user_signed_in?
      @message.is_user = true
    elsif company_signed_in?
      @message.is_user = false
    end
    @message.room_id = @room.id
    if @message.save
      redirect_to room_path(@room)
    else
      redirect_to room_path(@room)
    end
    end
    
    private
    
    def message_params
      params.require(:message).permit(:content)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new
    post = Post.new(post_params)
    post.user_id = current_user.id
    if post.save
    redirect_to post_path(post)
    else
      render 'new'
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end
  
  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    redirect_to post_path(@post)
  end
  
  private
    def post_params
     params.require(:post).permit(:title, :description, :post_image)
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  
  def index
    if user_signed_in?
      @companys = Company.all
      rooms = current_user.rooms
      @company_ids = []
      rooms.each do |r|
        @company_ids << r.company_id
      end
      
    elsif company_signed_in?
      @users = User.all
      rooms = current_company.rooms
      @user_ids = []
      rooms.each do |r|
        @user_ids << r.user_id
      end
    end
  end
  
  def show
    @room = Room.find(params[:id])
    @message = Message.new
    @messages = @room.messages
    if user_signed_in?
      if @room.user_id == current_user.id
       @company = Company.find(@room.company_id)
      else
       redirect_to rooms_path
      end
    elsif company_signed_in?
      if @room.company_id == current_company.id
        @user = User.find(@room.user_id)
      else
        redirect_to rooms_path
      end
      
    else
      redirect_to rooms_path
    end
  end

  def create
    if user_signed_in?
      @room = Room.new(room_company_params)
      @room.user_id = current_user.id
    elsif company_signed_in?
      @room = Room.new(room_user_params)
      @room.company_id = current_company.id
    else
      redirect_to rooms_path
    end
    
    if @room.save
      redirect_to :action => "show", :id => @room.id
    else
      redirect_to rooms_path
    end
  end
  
  private
  def room_company_params
    params.require(:room).permit(:company_id)
  end
  
  def room_user_params
    params.require(:room).permit(:user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/company_helper.rb
module CompanyHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contacts/confirm.html.erb
<div class="container">
<div>
  <h2 class="title">Contact Confirm</h2>
</div>
 
<%= form_for @contact, :url => contacts_thanks_path do |f| %>
  <table class="table">
    <tr>
      <th class="labels">名前</th>
      <td class="text">
        <%= f.hidden_field :name %>
        <%= @contact.name %>
      </td>
    </tr>
    <tr>
      <th class="labels">メールアドレス</th>
      <td class="text">
        <%= f.hidden_field :email %>
        <%= @contact.email %>
      </td>
    </tr>
    <tr>
      <th class="labels">お問い合わせ内容</th>
      <td class="text">
        <%= f.hidden_field :message %>
        <%= simple_format(@contact.message) %>
      </td>
    </tr>
  </table>
  <%= f.submit '送信', :class => 'btn btn-primary pull-right' %>
<% end %>
</div>

app/views/contacts/index.html.erb
<div class="container">
<%= form_for @contact, :url => contacts_confirm_path do |f| %>
  <div>
    <h2 class="title">Contact</h2>
  </div>
 
  <% if @contact.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <strong>入力内容にエラーがあります</strong>
      <ul>
        <% @contact.errors.each do |attr, msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<table class="table">
    <tr>
      <th>名前<span class="text-danger">（必須）</span></th>
      <td class="text"><%= f.text_field :name %></td>
    </tr>
    <tr>
      <th>メールアドレス<span class="text-danger">（必須）</span></th>
      <td class="text"><%= f.text_field :email %></td>
    </tr>
    <tr>
      <th>お問い合わせ内容<span class="text-danger">（必須）</span></th>
      <td class="text"><%= f.text_area :message %></td>
    </tr>
  </table>
  <div class="text-center contact_box">
  <%= f.submit '確認画面へ', class: 'btn btn-primary contact_btn' %>
  </div>
<% end %>
 </div>

app/views/contacts/thanks.html.erb
<div class="page-header">
  <h2 class="title">Contact Complete</h2>
</div>
<p class="text">
  お問い合わせいただきありがとうございました。
</p>

app/views/rooms/index.html.erb
<div class="container">
<h2 class="title">Message</h2>

<% if user_signed_in? %>
 <table class="table">
   <tbody>
     <% @companys.each do |company| %>
     <tr>
      <th><%= company.company_name %></th>
      <% if @company_ids.include?(company.id) %>
      <td><%= link_to "DMを送る", room_path(current_user.rooms.find_by(company_id: company.id)), class: "btn btn-primary pull-right" %></td>
      <% else %>
       <%= form_for Room.new do |f| %>
       <%= f.hidden_field :company_id, :value => company.id %>
       <td><%= f.submit 'DMを送る', class: "btn btn-dark pull-right" %></td>
       <% end %>
      <% end %>
      </tr>
     <% end %>
  </tbody>
  </table>
<!--companyでログインしてたら-->
<% else company_signed_in? %>
<table class="table">
  <tbody>
  <% @users.each do |user| %>
  <tr>
    <th><%= user.name %></th>
    <% if @user_ids.include?(user.id) %>
      <td><%= link_to "DMを送る", room_path(current_company.rooms.find_by(user_id: user.id)), class: "btn btn-primary pull-right" %></td>
    <% else %>
      <%= form_for Room.new do |f| %>
        <%= f.hidden_field :user_id, :value => user.id %>
        <td><%= f.submit 'DMを送る', class: "btn btn-dark pull-right" %></td>
      <% end %>
    <% end %>
    </tr>
  <% end %>
  </tbody>
  </table>
<% end %>

</div>

app/views/rooms/show.html.erb
<div class="container ">
<h2 class="title">Chatroom</h2>
<% if user_signed_in? %>
  <h3><%= @company.company_name %>とのチャットルーム</h3>
  <div class="chat-field">
    <% @messages.each do |m| %>
      <!-- メッセージがUserによるものだったら -->
      <% if m.is_user %>
        <!-- メッセージを右に寄せる -->
        <div class="message message_right">
          <span class="message_txt">
            <%= m.content %>
            </span>
        </div>
      <!-- メッセージがShopによるものだったら -->
      <% else %>
        <!-- メッセージを左に寄せる -->
        <div class="message message_left">
          <span class="message_txt">
            <%= m.content %>
            </span>
        </div>
      <% end %>
    <% end %>
  </div>
  <% elsif company_signed_in?%>
  <h3><%= @user.name %>とのチャットルーム</h3>
  <div class="chat-field">
    <% @messages.each do |m| %>
      <!-- メッセージがUserによるものだったら -->
      <% if m.is_user %>
        <!-- メッセージを左に寄せる -->
        <div class="message message_left">
          <span class="message_txt">
            <%= m.content %>
            </span>
        </div>
      <!-- メッセージがShopによるものだったら -->
      <% else %>
        <!-- メッセージを右に寄せる -->
        <div class="message message_right">
          <span class="message_txt">
            <%= m.content %>
            </span>
        </div>
      <% end %>
    <% end %>
  </div>
<% end %>

<%= form_for [@room, @message] do |f| %>
  <%= f.text_field :content, class: "message_form", placeholder: "メッセージを送信" %>
  <%= f.submit "送信", class: "message_submit" %>
<% end %>

<%= link_to 'DM一覧に戻る', rooms_path, class: "btn btn-primary pull-right message_btn" %>
</div>