config/routes.rb
Rails.application.routes.draw do
  
  root 'homes#top'
  get 'homes/about'
  get 'rooms/show'
  get 'rooms/index'
  
  devise_for :companys, controller: {
    sessions: "companys/sessions",
    passwords: "companys/passwords",
    registrations: "companys/registration"
 }
  
  resources :company, only:[:show, :edit, :update]
  
  get 'contacts/index'
  get 'contacts/confirm'
  get 'contacts/thanks'
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
  
  
  namespace :personal do
    resources :users, only:[:show, :edit, :update]
  end


  resources :posts do
      resource :favorites, only: [:create, :destroy]
  end
    
  get 'contacts' => 'contacts#index'
  post 'contacts/confirm' => 'contacts#confirm'
  post 'contacts/thanks' => 'contacts#thanks'


  resources :rooms, :only => [:index, :show, :create] do
    resources :messages, :only => [:create]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :rooms
  has_many :favorites, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  attachment :company_image
end

app/controllers/company_controller.rb
class CompanyController < ApplicationController
  
  def show
    @company = Company.find(params[:id])
    @favorites = Favorite.where(company_id: @company.id)
  end

  def edit
    @company = Company.find(params[:id])
  end

  def update
    @company = Company.find(params[:id])
    @company.update(company_params)
    redirect_to company_path(@company)
  end
  
  private
  def company_params
    params.require(:company).permit(:company_name, :description, :company_image)
  end
end

app/controllers/companys/confirmations_controller.rb
# frozen_string_literal: true

class Companys::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/companys/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Companys::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/companys/passwords_controller.rb
# frozen_string_literal: true

class Companys::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/companys/registrations_controller.rb
# frozen_string_literal: true

class Companys::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/companys/sessions_controller.rb
# frozen_string_literal: true

class Companys::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/companys/unlocks_controller.rb
# frozen_string_literal: true

class Companys::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/company_helper.rb
module CompanyHelper
end

app/views/company/edit.html.erb
<h2 class="title">Company Edit</h2>
<%= form_with model: @company, url: company_path, local: true do |f| %>

<div class="col-xs-6 display-center">
  <%= f.file_field :company_image %>
</div>

<div class="col-xs-6">
   <div class="form-group display-flex">
     <%= f.label :company_name, '会社名', class: "labels" %>
     <p class="text"><%= f.text_field :company_name %></p>
    </div>
    <div class="form-group display-flex">
      <%= f.label :description, '企業紹介', class: "labels" %>
      <p class="text"><%= f.text_area :description %></p>
    </div>
</div>
<div class="actions text-right">
    <%= f.submit '変更を保存', class: 'btn btn-primary' %>
    </div>
<% end %>

app/views/company/show.html.erb
<div class="container ">
<h2 class="title">Company</h2>

<% if company_signed_in? %>
<div class="col-xs-6 ">
    <%= attachment_image_tag @company, :company_image, size: '300x150', fallback: "no_image.png", size: "300x150" %>
    <p class="company_txt"><%= @company.company_name %></p>
    <p class="company_txt"><%= @company.description %></p>
    <%= link_to 'DM一覧へ', rooms_path, class: "btn btn-primary" %>
    <%= link_to '編集する', edit_company_path, class: "btn btn-success" %>
</div>

<div class="col-xs-6">
    <h3 class="title2">いいねした作品一覧</h3>
    <div class="company_block">
    <% @favorites.each do |favorite| %>
    <% post = Post.find_by(id: favorite.post_id) %>
    <div class="company_box">
    <%= link_to post_path(favorite.post_id) do %>
    <%= attachment_image_tag post, :post_image, size: '100x70', fallback: "no_image.png", size: "100x70" %>
    <% end %>
    <p class="company_tit"><%= post.title %></p>
    </div>
  <% end %>
  </div>
</div>

<% else user_signed_in? %>

<div class="col-xs-6">
    <%= attachment_image_tag @company, :company_image, size: '100x100', fallback: "no_image.png", size: "180x100" %>
    <p><%= @company.company_name %></p>
    <p><%= @company.description %></p>
</div>

<% end %>
</div>