config/routes.rb
Rails.application.routes.draw do
  
  root 'homes#top'
  get 'homes/about'
  get 'rooms/show'
  get 'rooms/index'
  
  devise_for :companys, controller: {
    sessions: "companys/sessions",
    passwords: "companys/passwords",
    registrations: "companys/registration"
 }
  
  resources :company, only:[:show, :edit, :update]
  
  get 'contacts/index'
  get 'contacts/confirm'
  get 'contacts/thanks'
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
  
  
  namespace :personal do
    resources :users, only:[:show, :edit, :update]
  end


  resources :posts do
      resource :favorites, only: [:create, :destroy]
  end
    
  get 'contacts' => 'contacts#index'
  post 'contacts/confirm' => 'contacts#confirm'
  post 'contacts/thanks' => 'contacts#thanks'


  resources :rooms, :only => [:index, :show, :create] do
    resources :messages, :only => [:create]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :rooms
  has_many :favorites, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  attachment :company_image
end

app/models/contact.rb
class Contact < ApplicationRecord
     include ActiveModel::Model
     attr_accessor :name, :email, :message
     
      validates :name, presence: true
      validates :email, presence: true
      validates :message, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :company
  belongs_to :post
end

app/models/message.rb
class Message < ApplicationRecord
    validates :content, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
    
    has_many :favorites, dependent: :destroy
    belongs_to :user
    
    validates :title, presence: true
    validates :description, presence: true
    
    attachment :post_image
  
  
  def favorited_by?(company)
    favorites.where(company_id: company.id).exists?
  end
  
end

app/models/room.rb
class Room < ApplicationRecord
    has_many :messages
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :rooms, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  attachment :profile_image
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
  def top
  @skip_footer = true
  end

  def about
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new
    post = Post.new(post_params)
    post.user_id = current_user.id
    if post.save
    redirect_to post_path(post)
    else
      render 'new'
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end
  
  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    redirect_to post_path(@post)
  end
  
  private
    def post_params
     params.require(:post).permit(:title, :description, :post_image)
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  
  def index
    if user_signed_in?
      @companys = Company.all
      rooms = current_user.rooms
      @company_ids = []
      rooms.each do |r|
        @company_ids << r.company_id
      end
      
    elsif company_signed_in?
      @users = User.all
      rooms = current_company.rooms
      @user_ids = []
      rooms.each do |r|
        @user_ids << r.user_id
      end
    end
  end
  
  def show
    @room = Room.find(params[:id])
    @message = Message.new
    @messages = @room.messages
    if user_signed_in?
      if @room.user_id == current_user.id
       @company = Company.find(@room.company_id)
      else
       redirect_to rooms_path
      end
    elsif company_signed_in?
      if @room.company_id == current_company.id
        @user = User.find(@room.user_id)
      else
        redirect_to rooms_path
      end
      
    else
      redirect_to rooms_path
    end
  end

  def create
    if user_signed_in?
      @room = Room.new(room_company_params)
      @room.user_id = current_user.id
    elsif company_signed_in?
      @room = Room.new(room_user_params)
      @room.company_id = current_company.id
    else
      redirect_to rooms_path
    end
    
    if @room.save
      redirect_to :action => "show", :id => @room.id
    else
      redirect_to rooms_path
    end
  end
  
  private
  def room_company_params
    params.require(:room).permit(:company_id)
  end
  
  def room_user_params
    params.require(:room).permit(:user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/company_helper.rb
module CompanyHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
<div class="footer_block">
        <p class="footer_txt">
            ©️FassionRoad
        </p>
</div>
</footer>

app/views/layouts/_header.html.erb
<h2 class="navbar-left header_logo">
    <% if user_signed_in? %>
    <%= link_to image_tag("logo.png", :size => "100x60"), posts_path, class: "" %>
    <% elsif company_signed_in? %>
    <%= link_to image_tag("logo.png", :size => "100x60"),company_path(current_company.id), class: "logo_txt" %>
    <% else %>
    <%= link_to image_tag("logo.png", :size => "100x60"), root_path %>
    <% end %>
  </h2>

  <nav>
    <ul class="nav nav-pills pull-right header_list">
      <% if user_signed_in? %>
       <!--メンバーログイン-->
        <li class="header_item">
          <%= link_to " My Page", personal_user_path(current_user), class: "header_btn" %>
        </li>
        <li class="header_item">
          <%= link_to " Post", posts_path, class: "header_btn" %>
        </li>
        <li class="header_item">
          <%= link_to " Contact", contacts_path, class: "header_btn" %>
        </li>
        <li class="header_item">
          <%= link_to " Log out", destroy_user_session_path, method: :delete, class: "header_btn" %>
        </li>
      <% elsif company_signed_in? %>
      <!--会社ログイン-->
        <li class="header_item">
          <%= link_to " Company", company_path(current_company), class: "header_btn" %>
        </li>
        <li class="header_item">
          <%= link_to " Post", posts_path, class: "header_btn" %>
        </li>
        <li class="header_item">
          <%= link_to " Contact", contacts_path, class: "header_btn" %>
        </li>
        <li class="header_item">
          <%= link_to " Log out", destroy_company_session_path, method: :delete, class: "header_btn" %>
        </li>
      <% else %>
      <!--ログインしていない-->
        <li class="header_item">
          <%= link_to " About", homes_about_path, class: "header_btn" %>
        </li>
        <li class="header_item">
          <%= link_to " Contact", contacts_path, class: "header_btn" %>
        </li>
      <% end %>
    </ul>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FassionRoad</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
  </head>

  <body>
    <header class="header">
      <%= render 'layouts/header' %>
    </header>
    <div class="main">
     <%= yield %>
    </div>
      <%= render 'layouts/footer' unless @skip_footer %>
  </body>
</html>